VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 224

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

--TODO - make this slower later to make game more challenging
PLAYER_WALK_SPEED = 40
MONSTER_WALK_SPEED = 40
SLIME_WALK_SPEED = 30

MAP_HEIGHT = VIRTUAL_HEIGHT

